# -*- coding: utf-8 -*-
"""targetsistemas - darcyneto_ex01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rHYeV7CCYPsZ7Zl8O3pRsdZqmhyu60V
"""

def fibonacci(n):
    # verifica se o número dado pertence à sequência de Fibonacci
    if n < 0:
        return False

    a, b = 0, 1
    fibonacci_sequence = [a]  # Lista para armazenar a sequência

    # Gerando a sequência de Fibonacci até o valor ser maior ou igual ao número dado
    while a < n:
        a, b = b, a + b
        fibonacci_sequence.append(a)

    # Exibindo a sequência de Fibonacci gerada
    print(f"Sequência de Fibonacci até {n}: {fibonacci_sequence}")

    # Retorna True se o número pertence à sequência, caso contrário False
    return a == n

# Definindo o número diretamente no código
numero = 34
resultado = fibonacci(numero)

# Exibindo a mensagem de acordo com o resultado
mensagem = f"O número {numero} {'pertence' if resultado else 'não pertence'} à sequência de Fibonacci."
mensagem